### ISSUE TITLE
Option for updating tags for mp4 movie files?

### ISSUE THREAD

**Issue by michaelaguiar** [philiphardy/ID3Edit#2]
I'm looking for a solution to edit ID3 tags for movie files on the fly.  AVAsset works, but It re-saves the file on every edit, which takes too long vs just saving the tags to the existing file

**Comment by philiphardy** [comment]
I will look into this after I add compatibility for v3 ID3 tags on mp3 files.

**Comment by philiphardy** [comment]
What is the video format you are interested in?

**Comment by michaelaguiar** [comment]
Mainly M4V / MP4.

**Comment by michaelaguiar** [comment]
What exactly does this entail?  What are the major difference between an mp4 and an mp3?

**Comment by philiphardy** [comment]
I do not know the technical details between these two file types. However, if mp4 has ID3 information stored similarly to the way mp3 does (which I'm guessing it does), this should be a plausible task. If there is enough padding in the tag to account for the new information, updating the tags should only take overwriting the previous information with the updated information in the mp4 file. However, if there is not enough padding, I believe the whole file will have to be re-written.

I know it's almost a year since you posted, so let me know if you found a solution or if this is still something you are seeking answers to.

**Comment by michaelaguiar** [comment]
I haven't looked at this in a while actually.  I believe mp4 does store ID3 information similar to mp3.

I'm not too sure about the padding in the tag, but the only way I've been able to make it work is rebuilding the file, which takes a bit of time.  Would be ideal to figure out how to just write the ID3 data without rewriting the file so that we can scan multiple files quickly.

I will try and mess around with it more to see what I can find.
